src/Entity/WeatherData.php
<?php

namespace App\Entity;

use App\Repository\WeatherDataRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WeatherDataRepository::class)
 */
class WeatherData
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $temp_K;

    /**
     * @ORM\Column(type="integer")
     */
    private $humidity_percentage;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTempK(): ?float
    {
        return $this->temp_K;
    }

    public function setTempK(float $temp_K): self
    {
        $this->temp_K = $temp_K;

        return $this;
    }

    public function getHumidityPercentage(): ?int
    {
        return $this->humidity_percentage;
    }

    public function setHumidityPercentage(int $humidity_percentage): self
    {
        $this->humidity_percentage = $humidity_percentage;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/WeatherDataType.php
<?php

namespace App\Form;

use App\Entity\WeatherData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WeatherDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('temp_K')
            ->add('humidity_percentage')
            ->add('time')
            ->add('date')
            ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WeatherData::class,
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/default", name="default")
     */
    public function index()
    {
        return $this->render('default/index.html.twig', [

        ]);
    }
}

src/Controller/WeatherDataController.php
<?php

namespace App\Controller;

use App\Entity\WeatherData;
use App\Form\WeatherDataType;
use App\Repository\WeatherDataRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/weather/data")
 */
class WeatherDataController extends AbstractController
{
    /**
     * @Route("/", name="weather_data_index", methods={"GET"})
     */
    public function index(WeatherDataRepository $weatherDataRepository): Response
    {
        return $this->render('weather_data/index.html.twig', [
            'weather_datas' => $weatherDataRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="weather_data_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $weatherDatum = new WeatherData();
        $form = $this->createForm(WeatherDataType::class, $weatherDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($weatherDatum);
            $entityManager->flush();

            return $this->redirectToRoute('weather_data_index');
        }

        return $this->render('weather_data/new.html.twig', [
            'weather_datum' => $weatherDatum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="weather_data_show", methods={"GET"})
     */
    public function show(WeatherData $weatherDatum): Response
    {
        return $this->render('weather_data/show.html.twig', [
            'weather_datum' => $weatherDatum,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="weather_data_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, WeatherData $weatherDatum): Response
    {
        $form = $this->createForm(WeatherDataType::class, $weatherDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('weather_data_index');
        }

        return $this->render('weather_data/edit.html.twig', [
            'weather_datum' => $weatherDatum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="weather_data_delete", methods={"DELETE"})
     */
    public function delete(Request $request, WeatherData $weatherDatum): Response
    {
        if ($this->isCsrfTokenValid('delete'.$weatherDatum->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($weatherDatum);
            $entityManager->flush();
        }

        return $this->redirectToRoute('weather_data_index');
    }
}

src/Controller/WeatherLoggerController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class WeatherLoggerController extends AbstractController
{
    /**
     * @Route("/weather/logger", name="weather_logger")
     */
    public function index()
    {
        return $this->render('weather_logger/index.html.twig', [
            'controller_name' => 'WeatherLoggerController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome to the WeatherLogger{% endblock %}</title>
        {% block stylesheets %}
            {# 'app' must match the first argument to addEntry() in webpack.config.js #}
            {{ encore_entry_link_tags('app') }}

            <!-- Renders a link tag (if your module requires any CSS)
                 <link rel="stylesheet" href="/build/app.css"> -->
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
        {{ knp_menu_render('main', {'rootClass': 'navbar-nav'}) }}
        </div>
    </nav>
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}

            <!-- Renders app.js & a webpack runtime.js file
                <script src="/build/runtime.js"></script>
                <script src="/build/app.js"></script> -->
        {% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello there!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello there!</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/alex/Dokumente/programmierung/weather_logger/src/Controller/DefaultController.php'|file_link(0) }}">src/Controller/DefaultController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/alex/Dokumente/programmierung/weather_logger/templates/default/index.html.twig'|file_link(0) }}">templates/default/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/menu/main_menu.html.twig
{% block list %}
    {% if item.hasChildren and options.depth is not same as(0) and item.displayChildren %}
        {% import 'knp_menu.html.twig' as knp_menu %}
        <ul{{ knp_menu.attributes(listAttributes|merge({'class': [
            options.rootClass is defined ? options.rootClass : '',
            listAttributes.class is defined ? listAttributes.class : ''
        ]|join(' ')
        })) }}>
            {% set options = options|merge({'rootClass': '' }) %}
            {{ block('children') }}
        </ul>
    {% endif %}
{% endblock %}

templates/weather_data/_delete_form.html.twig
<form method="post" action="{{ path('weather_data_delete', {'id': weather_datum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ weather_datum.id) }}">
    <button class="btn">Delete</button>
</form>

templates/weather_data/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/weather_data/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WeatherData{% endblock %}

{% block body %}
    <h1>Edit WeatherData</h1>

    {{ include('weather_data/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('weather_data_index') }}">back to list</a>

    {{ include('weather_data/_delete_form.html.twig') }}
{% endblock %}

templates/weather_data/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherData index{% endblock %}

{% block body %}
    <h1>WeatherData index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Temp_K</th>
                <th>Humidity_percentage</th>
                <th>Time</th>
                <th>Date</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for weather_datum in weather_datas %}
            <tr>
                <td>{{ weather_datum.id }}</td>
                <td>{{ weather_datum.tempK }}</td>
                <td>{{ weather_datum.humidityPercentage }}</td>
                <td>{{ weather_datum.time ? weather_datum.time|date('H:i:s') : '' }}</td>
                <td>{{ weather_datum.date ? weather_datum.date|date('Y-m-d') : '' }}</td>
                <td>{{ weather_datum.createdAt ? weather_datum.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('weather_data_show', {'id': weather_datum.id}) }}">show</a>
                    <a href="{{ path('weather_data_edit', {'id': weather_datum.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('weather_data_new') }}">Create new</a>
{% endblock %}

templates/weather_data/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New WeatherData{% endblock %}

{% block body %}
    <h1>Create new WeatherData</h1>

    {{ include('weather_data/_form.html.twig') }}

    <a href="{{ path('weather_data_index') }}">back to list</a>
{% endblock %}

templates/weather_data/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherData{% endblock %}

{% block body %}
    <h1>WeatherData</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ weather_datum.id }}</td>
            </tr>
            <tr>
                <th>Temp_K</th>
                <td>{{ weather_datum.tempK }}</td>
            </tr>
            <tr>
                <th>Humidity_percentage</th>
                <td>{{ weather_datum.humidityPercentage }}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td>{{ weather_datum.time ? weather_datum.time|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ weather_datum.date ? weather_datum.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ weather_datum.createdAt ? weather_datum.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('weather_data_index') }}">back to list</a>

    <a href="{{ path('weather_data_edit', {'id': weather_datum.id}) }}">edit</a>

    {{ include('weather_data/_delete_form.html.twig') }}
{% endblock %}

templates/weather_logger/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WeatherLoggerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/alex/Dokumente/programmierung/weather_logger/src/Controller/WeatherLoggerController.php'|file_link(0) }}">src/Controller/WeatherLoggerController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/alex/Dokumente/programmierung/weather_logger/templates/weather_logger/index.html.twig'|file_link(0) }}">templates/weather_logger/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}